name = "Solarized Dark"
mode = "dark"
font = "Maple Mono NF"

[colors]
wall = "#00212b"
wall2 = "#002b36"
bar = "#073642"
term = "#002b36"
fg = "#93a1a1"
dim = "#586e75"
accent = "#268bd2"
red = "#dc322f"
orange = "#cb4b16"
yellow = "#b58900"
green = "#859900"
cyan = "#2aa198"
magenta = "#d33682"
sel = "#073642"
