name = "Oxocarbon"
mode = "dark"
font = "Maple Mono NF"

[colors]
wall = "#0b0b0b"
wall2 = "#161616"
bar = "#161616"
term = "#161616"
fg = "#f2f4f8"
dim = "#525252"
accent = "#78a9ff"
red = "#ee5396"
orange = "#ff7eb6"
yellow = "#82cfff"
green = "#42be65"
cyan = "#3ddbd9"
magenta = "#be95ff"
sel = "#262626"
