name = "Catppuccin Latte"
mode = "light"
twin = "catppuccin-mocha"

[colors]
wall = "#dce0e8"
wall2 = "#eff1f5"
bar = "#e6e9ef"
term = "#eff1f5"
fg = "#4c4f69"
dim = "#8c8fa1"
accent = "#1e66f5"
red = "#d20f39"
orange = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
cyan = "#179299"
magenta = "#8839ef"
sel = "#ccd0da"
