name = "Catppuccin Mocha"
mode = "dark"
twin = "catppuccin-latte"

[colors]
wall = "#11111b"
wall2 = "#1e1e2e"
bar = "#181825"
term = "#1e1e2e"
fg = "#cdd6f4"
dim = "#7f849c"
accent = "#89b4fa"
red = "#f38ba8"
orange = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
cyan = "#94e2d5"
magenta = "#cba6f7"
sel = "#313244"
