name = "Rosé Pine Dawn"
mode = "light"
twin = "rose-pine"
font = "Maple Mono NF"

[colors]
wall = "#f2e9e1"
wall2 = "#faf4ed"
bar = "#fffaf3"
term = "#faf4ed"
fg = "#575279"
dim = "#9893a5"
accent = "#907aa9"
red = "#b4637a"
orange = "#ea9d34"
yellow = "#ea9d34"
green = "#56949f"
cyan = "#56949f"
magenta = "#907aa9"
sel = "#dfdad9"
