# Change the prefix key from C-A to C-Space
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Make <Leader>Space Reload the config
bind r source-file ~/.config/tmux/.tmux.conf \; display "Config Reloaded!"

# Enable mouse support
set -g mouse on
