name = "Kanagawa Lotus"
mode = "light"
twin = "kanagawa-wave"

[colors]
wall = "#e7dba0"
wall2 = "#f2ecbc"
bar = "#e4d794"
term = "#f2ecbc"
fg = "#545464"
dim = "#8a8980"
accent = "#4d699b"
red = "#c84053"
orange = "#cc6d00"
yellow = "#77713f"
green = "#6f894e"
cyan = "#597b75"
magenta = "#624c83"
sel = "#c9cbd1"
